# This is a basic workflow to help you get started with Actions for Golang application

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Define variables
        run: |
          echo ::set-env name=PROJECT::$(echo "golang-github-action")
          echo ::set-env name=VERSION::$(git describe --tags)
          echo ::set-env name=COMMIT::$(git rev-parse HEAD)
          echo ::set-env name=BUILDTIME::$(date +%FT%T%z)

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        run: docker build --build-arg TOKEN=${TOKEN} --build-arg VERSION=${VERSION} --build-arg COMMIT=${COMMIT} --build-arg BUILDTIME=${BUILDTIME} -t ${DOCKER_USERNAME}/${PROJECT}:${IMAGE_TAG} .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Push to docker hub
        uses: actions-hub/docker@master
        with:
          args: push ${DOCKER_USERNAME}/${PROJECT}:${IMAGE_TAG}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
